import 'package:dio/dio.dart';

import 'log_entry_dto.dart';

/// The network client for the logs endpoint.
///
/// In production this is generated by retrofit (Dart) — `@RestApi` plus
/// `@GET`, `@POST` annotations. The sample is hand-written.
///
/// LogsApi is a thin shim over Dio. It does NOT translate exceptions to
/// Failures — that's the Repository's job. LogsApi may throw DioException,
/// FormatException, or anything else. The Repository catches.
class LogsApi {
  LogsApi(this._dio);

  final Dio _dio;

  Future<List<LogEntryDto>> fetchAll() async {
    final response = await _dio.get<List<dynamic>>('/logs');
    final data = response.data ?? const [];
    return data
        .map((e) => LogEntryDto.fromJson(e as Map<String, dynamic>))
        .toList(growable: false);
  }

  Future<LogEntryDto> create({
    required String title,
    required String body,
    required String category,
  }) async {
    final response = await _dio.post<Map<String, dynamic>>(
      '/logs',
      data: {'title': title, 'body': body, 'category': category},
    );
    return LogEntryDto.fromJson(response.data!);
  }
}
